### ISSUE TITLE
Quiz Form Challenge!!

### ISSUE THREAD

**Issue by shashankpatil28** [opencodeiiita/GrepIt-Frontend#17] opened 2023-12-15 20:18 UTC
### we have a Task for you. this is about How the quiz will be made.

**Task Details:**

Your task is to create a **quizForm** component that contains various input boxes. Details are given below

**#Details**

1. The components' rough design is given below. Add your creativity and make its Ux as good as possible.
2. The "correct option no." button must take a number as input which is correct. 
3. on submitting the question form, make a separate div below the form that shows the question, its option and correct answer.
4. Responsiveness is mandatory.
5. Store the quiz data as a request for backend purposes.
6. Use the proper props.

NOTE: use of antDesign will be appreciated through points.

![image](https://github.com/opencodeiiita/GrepIt-Frontend/assets/122175701/0652ea7d-f7e3-40b5-9543-8c490ca3ef0c)

> File Location: Write the component in src/components/quizForm.jsx
> Router Placement: Integrate the component into the app router with the path '/quiz' and place it properly at the center.

Comment to Claim for the task.

**Comment by ShauryaJain03** [comment] 2023-12-15 20:19
claim

**Comment by Rohit-110** [comment] 2023-12-15 20:19
claim

**Comment by QuantTitan** [comment] 2023-12-15 20:19
claim

**Comment by atharva0192** [comment] 2023-12-15 20:20
claim

**Comment by shashankpatil28** [comment] 2023-12-15 20:25
@ShauryaJain03 The Task is assigned to you, Congrats. Kindly go through the details made make it completion ASAP. if any query message me on Discord.

**Comment by ShauryaJain03** [comment] 2023-12-17 18:55
@shashankpatil28 I would have to unassign myself as I have to go somewhere, really sorry for the inconvenience caused.

**Comment by rnavaneeth992** [comment] 2023-12-17 18:56
Claim

**Comment by rnavaneeth992** [comment] 2023-12-17 19:00
I want to do this, I have already one task it is already completed, I told in discord, if ok na I will create PR and you can merge and assign this 🥺

**Comment by WadadParker** [comment] 2023-12-17 19:16
Claim

**Comment by bhupesh98** [comment] 2023-12-17 20:02
As the issue is reopened, first claim after this message assuring timely completing of the task will be assigned.

**Comment by kushal7201** [comment] 2023-12-17 20:02
Claim

**Comment by sarthakvermaa** [comment] 2023-12-17 20:03
claim

**Comment by rnavaneeth992** [comment] 2023-12-17 20:03
claim

**Comment by bhupesh98** [comment] 2023-12-17 20:05
> Claim

Heyy @kushal7201 as you have reached the limit of 3 assignable task, I can't assign you this task.

**Comment by bhupesh98** [comment] 2023-12-17 20:05
> claim

@sarthakvermaa Assigned
Mention your discord ID so you can discuss with us regarding the issue and we can keep track of it.

**Comment by ajay484** [comment] 2023-12-17 21:24
Claim

**Comment by sarthakvermaa** [comment] 2023-12-18 02:33
> > claim
> 
> @sarthakvermaa Assigned
> Mention your discord ID so you can discuss with us regarding the issue and we can keep track of it.

sartirexd

**Comment by sarthakvermaa** [comment] 2023-12-20 07:22
@bhupesh98 Due to travelling I won't be able to finish this. Please unassign me.

**Comment by bhupesh98** [comment] 2023-12-20 07:28
This issue is open for claim once again.
We need to complete this task as soon as possible. Timely claim and PR for this issue will be rewarded with bonus points.
Claim comment from now on will be considered for assigning the task.

**Comment by kushal7201** [comment] 2023-12-20 07:29
Claim

**Comment by ssugam10** [comment] 2023-12-20 07:29
claim

**Comment by Nandinig24** [comment] 2023-12-20 07:30
Claim

**Comment by rnavaneeth992** [comment] 2023-12-20 07:30
Claim

**Comment by bhupesh98** [comment] 2023-12-20 07:36
@kushal7201 As I can see you already got a task from this repo, so assigning the next person which is @ssugam10.

**Closed as completed** 2023-12-22 19:12 UTC
Labels: Points: 20, Skilled
